name: Backup Supabase DB

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 3:00 UTC
  workflow_dispatch:     # Permite ejecutar manualmente

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      PGHOST: db.cbrxgjksefmgtoatkbbs.supabase.co
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: TU_USUARIO
      PGPASSWORD: TU_PASSWORD

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Crear carpeta de backups
        run: mkdir -p backups

      - name: Obtener timestamp
        id: date
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Hacer dump con pg_dump
        run: |
          docker run --rm \
            -e PGHOST=$PGHOST \
            -e PGPORT=$PGPORT \
            -e PGDATABASE=$PGDATABASE \
            -e PGUSER=$PGUSER \
            -e PGPASSWORD=$PGPASSWORD \
            postgres:15 \
            pg_dump --no-owner --no-acl -Fc -f /backup/backup_$TIMESTAMP.dump \
            -h $PGHOST -U $PGUSER -d $PGDATABASE
        env:
          TIMESTAMP: ${{ steps.date.outputs.timestamp }}
        volumeMounts:
          - name: backup-volume
            mountPath: /backup

      - name: Mover backup al repo
        run: |
          mv /home/runner/work/backuppetoclub/backuppetoclub/backup_*.dump backups/

      - name: Hacer commit del backup
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add backups/
          git commit -m "Backup automático ${{ steps.date.outputs.timestamp }}" || echo "Sin cambios"
          git push