name: Backup Supabase DB

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: self-hosted

    steps:
      - name: Crear carpeta backups si no existe
        run: |
          if (-Not (Test-Path -Path backups)) {
            mkdir backups
          } else {
            Write-Host "La carpeta backups ya existe."
          }
        shell: powershell

      - name: Descargar y descomprimir Supabase CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/supabase/cli/releases/download/v1.59.3/supabase_x86_64-pc-windows-msvc.zip -OutFile supabase.zip
          Expand-Archive -Path supabase.zip -DestinationPath ./supabase-cli
        shell: powershell

      - name: Agregar Supabase CLI al PATH
        run: echo "::add-path::$(pwd)/supabase-cli"
        shell: powershell

      - name: Ejecutar backup con Supabase CLI
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          ./supabase-cli/supabase db dump --file backups/backup-$(Get-Date -Format "yyyyMMddHHmmss").sql
        shell: powershell
