name: Backup Supabase DB con Docker en Windows runner

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: self-hosted

    steps:
      - name: Crear carpeta backups si no existe
        shell: powershell
        run: |
          if (-not (Test-Path -Path backups)) {
            New-Item -ItemType Directory -Path backups
          } else {
            Write-Host "La carpeta backups ya existe."
          }

      - name: Ejecutar pg_dump con Docker
        shell: powershell
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          docker run --rm -v ${PWD}:/backup postgres:15 pg_dump $Env:SUPABASE_DB_URL > backups/backup-$timestamp.sql