name: Backup Supabase DB

on:
  workflow_dispatch:  # Para poder lanzar manualmente

jobs:
  backup:
    runs-on: self-hosted  # Usamos el runner que configuraste (Windows)

    steps:
      - name: Crear carpeta backups
        run: mkdir backups
        shell: powershell

      - name: Descargar y descomprimir Supabase CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/supabase/cli/releases/latest/download/supabase_windows_amd64.zip -OutFile supabase.zip
          Expand-Archive -Path supabase.zip -DestinationPath ./supabase-cli
        shell: powershell

      - name: Agregar Supabase CLI al PATH
        run: echo "::add-path::$(pwd)/supabase-cli"

