name: Supabase Backup

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -OutFile supabase.tar.gz
tar -xzf supabase.tar.gz
          sudo mv supabase /usr/local/bin/supabase

      - name: Create DB backup
        run: |
          mkdir -p backups
          supabase db dump --db-url ${{ secrets.SUPABASE_DB_URL }} > backups/backup_$(date +'%Y-%m-%d_%H-%M-%S').sql

      - name: Commit and push backup
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add backups/
          git commit -m "Backup: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push

